#!/usr/bin/env python3

"""Generate deterministic RGB565 assets for the Gemini S1 choice screen."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageOps


APPROVED = {
    "sitting.png": (
        "b662dc623695ebf1f8044e9b1d1101056a504a6820cdafea9f21cb2dbb8577f9",
        (1086, 1448),
    ),
    "homedinner.png": (
        "0e033242db21a2d8e974c6b012ace82201e5678cbad94cf47f4dc098767dfbe3",
        (1254, 1254),
    ),
    "mystery_box_ui.png": (
        "e73f0226adc3f30e289317d5315a66e42ff74ecd0e3ff9800e4453174c2204dd",
        (1024, 1024),
    ),
    "takeout_bag_ui.png": (
        "23519c2f7a565d5252a706c10a82df359e36126e93ffd1bfbb45d3309a51aff9",
        (1024, 1024),
    ),
}

BACKGROUND_PORTRAIT = (240, 320)
BACKGROUND_LANDSCAPE = (320, 240)
CARD_SIZE = (64, 64)
CARD_BACKGROUND = (246, 225, 194, 255)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _verify_source(source_dir: Path, name: str) -> Path:
    path = source_dir / name
    expected_digest, expected_size = APPROVED[name]
    if not path.is_file():
        raise ValueError(f"missing approved source: {path}")
    if _sha256(path) != expected_digest:
        raise ValueError(f"source digest does not match approval: {name}")
    with Image.open(path) as image:
        if image.size != expected_size:
            raise ValueError(f"source geometry does not match approval: {name}")
    return path


def _background(path: Path, size: tuple[int, int]) -> Image.Image:
    with Image.open(path) as source:
        return ImageOps.fit(
            source.convert("RGB"),
            size,
            method=Image.Resampling.LANCZOS,
            centering=(0.5, 0.5),
        )


def _card(path: Path) -> Image.Image:
    with Image.open(path) as source:
        icon = ImageOps.contain(
            source.convert("RGBA"),
            (56, 56),
            method=Image.Resampling.LANCZOS,
        )
    canvas = Image.new("RGBA", CARD_SIZE, CARD_BACKGROUND)
    offset = ((CARD_SIZE[0] - icon.width) // 2, (CARD_SIZE[1] - icon.height) // 2)
    canvas.alpha_composite(icon, offset)
    return canvas.convert("RGB")


def _rgb565_le(image: Image.Image) -> bytes:
    output = bytearray(image.width * image.height * 2)
    cursor = 0
    pixels = image.load()
    for y in range(image.height):
        for x in range(image.width):
            red, green, blue = pixels[x, y]
            pixel = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
            output[cursor] = pixel & 0xFF
            output[cursor + 1] = pixel >> 8
            cursor += 2
    return bytes(output)


def _format_array(name: str, data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("  " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return (
        f"const uint8_t {name}[{len(data)}] =\n"
        "{\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def _header() -> str:
    return """#ifndef LIVING_CANVAS_GENERATED_LC_CHOICE_ASSETS_H
#define LIVING_CANVAS_GENERATED_LC_CHOICE_ASSETS_H

#include <stdint.h>

#define LC_BG_PORTRAIT_WIDTH 240u
#define LC_BG_PORTRAIT_HEIGHT 320u
#define LC_BG_PORTRAIT_BYTES 153600u
#define LC_BG_LANDSCAPE_WIDTH 320u
#define LC_BG_LANDSCAPE_HEIGHT 240u
#define LC_BG_LANDSCAPE_BYTES 153600u
#define LC_CARD_WIDTH 64u
#define LC_CARD_HEIGHT 64u
#define LC_CARD_BYTES 8192u

extern const uint8_t lc_bg_portrait[LC_BG_PORTRAIT_BYTES];
extern const uint8_t lc_bg_landscape[LC_BG_LANDSCAPE_BYTES];
extern const uint8_t lc_card_takeout[LC_CARD_BYTES];
extern const uint8_t lc_card_mystery[LC_CARD_BYTES];
extern const uint8_t lc_card_home[LC_CARD_BYTES];

#endif
"""


def _source(arrays: Iterable[tuple[str, bytes]]) -> str:
    parts = [
        '#include "generated/lc_choice_assets.h"\n\n',
        "/* Generated by tools/convert_choice_assets.py. Do not edit. */\n\n",
    ]
    for name, data in arrays:
        parts.append(_format_array(name, data))
        parts.append("\n")
    parts.extend(
        [
            "_Static_assert(sizeof(lc_bg_portrait) == LC_BG_PORTRAIT_BYTES,\n",
            '               "portrait asset size mismatch");\n',
            "_Static_assert(sizeof(lc_bg_landscape) == LC_BG_LANDSCAPE_BYTES,\n",
            '               "landscape asset size mismatch");\n',
            "_Static_assert(sizeof(lc_card_takeout) == LC_CARD_BYTES,\n",
            '               "takeout card size mismatch");\n',
            "_Static_assert(sizeof(lc_card_mystery) == LC_CARD_BYTES,\n",
            '               "mystery card size mismatch");\n',
            "_Static_assert(sizeof(lc_card_home) == LC_CARD_BYTES,\n",
            '               "home card size mismatch");\n',
        ]
    )
    return "".join(parts)


def generate_files(source_dir: Path, output_c: Path, output_h: Path) -> dict[str, int]:
    paths = {name: _verify_source(source_dir, name) for name in APPROVED}
    arrays = [
        (
            "lc_bg_portrait",
            _rgb565_le(_background(paths["sitting.png"], BACKGROUND_PORTRAIT)),
        ),
        (
            "lc_bg_landscape",
            _rgb565_le(_background(paths["sitting.png"], BACKGROUND_LANDSCAPE)),
        ),
        ("lc_card_takeout", _rgb565_le(_card(paths["takeout_bag_ui.png"]))),
        ("lc_card_mystery", _rgb565_le(_card(paths["mystery_box_ui.png"]))),
        ("lc_card_home", _rgb565_le(_card(paths["homedinner.png"]))),
    ]

    output_c.parent.mkdir(parents=True, exist_ok=True)
    output_h.parent.mkdir(parents=True, exist_ok=True)
    output_c.write_text(_source(arrays), encoding="utf-8", newline="\n")
    output_h.write_text(_header(), encoding="utf-8", newline="\n")
    return {
        "portrait_background_bytes": len(arrays[0][1]),
        "landscape_background_bytes": len(arrays[1][1]),
        "card_bytes": len(arrays[2][1]),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output-c", type=Path, required=True)
    parser.add_argument("--output-h", type=Path, required=True)
    args = parser.parse_args()
    summary = generate_files(args.source_dir, args.output_c, args.output_h)
    print(
        "generated "
        f"portrait={summary['portrait_background_bytes']} "
        f"landscape={summary['landscape_background_bytes']} "
        f"card={summary['card_bytes']}"
    )


if __name__ == "__main__":
    main()
